create table if not exists public.archive_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  year integer,
  category text not null default 'anime',
  rating numeric default 0,
  genres text[] default '{}',
  status text default 'must-watch',
  favourite boolean default false,
  cover text,
  youtube text,
  synopsis text,
  created_at timestamptz default now()
);

alter table public.archive_items enable row level security;

drop policy if exists "Users can read their own archive" on public.archive_items;
drop policy if exists "Users can add to their own archive" on public.archive_items;
drop policy if exists "Users can update their own archive" on public.archive_items;
drop policy if exists "Users can delete their own archive" on public.archive_items;

create policy "Users can read their own archive"
on public.archive_items for select to authenticated
using (auth.uid() = user_id);

create policy "Users can add to their own archive"
on public.archive_items for insert to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own archive"
on public.archive_items for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own archive"
on public.archive_items for delete to authenticated
using (auth.uid() = user_id);

create index if not exists archive_items_user_id_index
on public.archive_items(user_id);
